## Importando bibliotecas e o Dataset

In [188]:
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [189]:
dt = pd.read_csv('winequality-white.csv', delimiter=';')

In [190]:
dt.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

## Construindo modelo com SGDRegressor

In [191]:
labels = dt.values[:, -1]
features = dt.values[:, 0:-1]

In [192]:
X_train, X_test, y_train, y_test= train_test_split(features, labels, test_size=0.2, stratify=labels, random_state=42)

In [193]:
model = SGDRegressor()
model.fit(X_train, y_train)

SGDRegressor()

In [194]:
y_predicted_train = model.predict(X_train)

squared_error = np.sqrt(mean_squared_error(y_train, y_predicted_train))
print("Mean Squared Error: {}".format(squared_error))
absolute_error = np.sqrt(mean_absolute_error(y_train, y_predicted_train))
print("Mean Absolute Error: {}".format(absolute_error))

Mean Squared Error: 7965220603434.88
Mean Absolute Error: 2756665.0894530904


In [195]:
y_predicted = model.predict(X_test)

squared_error = np.sqrt(mean_squared_error(y_test, y_predicted))
print("Mean Squared Error: {}".format(squared_error))
absolute_error = np.sqrt(mean_absolute_error(y_test, y_predicted))
print("Mean Absolute Error: {}".format(absolute_error))

Mean Squared Error: 7984104437350.172
Mean Absolute Error: 2760676.270061602


In [196]:
y_predicted

array([-8.96962097e+12, -7.61319861e+12, -5.97705752e+12, -5.00550278e+12,
       -7.88084982e+12, -7.28748377e+12, -5.83360716e+12, -8.62812016e+12,
       -1.03487630e+13, -9.06078977e+12, -5.27039209e+12, -8.51231095e+12,
       -8.08719659e+12, -4.37974460e+12, -9.15342396e+12, -7.41919651e+12,
       -7.01569905e+12, -6.53015676e+12, -3.69880670e+12, -5.86504147e+12,
       -7.99080268e+12, -5.72642665e+12, -7.37716615e+12, -1.13915487e+13,
       -9.41369834e+12, -5.23546230e+12, -9.37821459e+12, -6.06758909e+12,
       -7.43906035e+12, -9.89435386e+12, -6.63366330e+12, -5.06149008e+12,
       -6.16218238e+12, -5.30629964e+12, -5.02300777e+12, -4.91528636e+12,
       -7.03806638e+12, -8.20685587e+12, -3.97185839e+12, -1.24438321e+13,
       -7.14281245e+12, -4.63137849e+12, -1.03000769e+13, -1.15956820e+13,
       -7.23226620e+12, -9.51362879e+12, -7.72157183e+12, -8.22046465e+12,
       -7.54363009e+12, -6.54248754e+12, -7.11239086e+12, -7.99080268e+12,
       -7.23783351e+12, -

In [197]:
y_test

array([6., 7., 6., 6., 8., 5., 7., 6., 5., 5., 7., 6., 6., 6., 5., 4., 5.,
       5., 4., 6., 6., 7., 5., 6., 6., 6., 6., 6., 5., 6., 7., 6., 6., 7.,
       6., 5., 6., 7., 5., 6., 6., 4., 7., 3., 5., 5., 6., 6., 6., 6., 6.,
       6., 7., 6., 6., 7., 6., 5., 3., 5., 6., 6., 7., 5., 5., 6., 5., 6.,
       6., 5., 6., 6., 5., 6., 6., 5., 6., 6., 6., 6., 5., 4., 7., 5., 5.,
       7., 5., 6., 5., 7., 8., 6., 5., 5., 5., 6., 6., 5., 7., 5., 5., 6.,
       5., 4., 4., 6., 7., 7., 5., 5., 5., 5., 5., 6., 5., 8., 5., 7., 6.,
       6., 6., 5., 5., 6., 6., 6., 6., 7., 6., 5., 5., 6., 5., 6., 7., 8.,
       5., 6., 6., 5., 7., 6., 4., 5., 6., 5., 6., 6., 8., 6., 6., 6., 5.,
       4., 6., 6., 5., 7., 6., 6., 5., 7., 6., 7., 4., 5., 6., 6., 9., 5.,
       5., 5., 5., 7., 7., 6., 6., 6., 5., 6., 6., 6., 8., 5., 6., 6., 7.,
       7., 6., 6., 5., 7., 6., 7., 6., 7., 6., 5., 7., 5., 6., 5., 6., 5.,
       7., 6., 6., 7., 5., 5., 4., 6., 4., 6., 3., 6., 5., 7., 7., 5., 6.,
       6., 5., 6., 6., 5.

## Construindo modelo com LinearRegression

In [198]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [199]:
y_predicted_train = model.predict(X_train)

squared_error = np.sqrt(mean_squared_error(y_train, y_predicted_train))
print("Mean Squared Error: {}".format(squared_error))
absolute_error = np.sqrt(mean_absolute_error(y_train, y_predicted_train))
print("Mean Absolute Error: {}".format(absolute_error))

Mean Squared Error: 0.7479704442845192
Mean Absolute Error: 0.7628438046403424


In [200]:
y_predicted = model.predict(X_test)

squared_error = np.sqrt(mean_squared_error(y_test, y_predicted))
print("Mean Squared Error: {}".format(squared_error))
absolute_error = np.sqrt(mean_absolute_error(y_test, y_predicted))
print("Mean Absolute Error: {}".format(absolute_error))

Mean Squared Error: 0.7611750693333428
Mean Absolute Error: 0.7687158402846896


In [201]:
y_predicted


array([5.22231143, 6.42715953, 5.72255586, 6.13622435, 7.14144627,
       5.9443972 , 5.87463164, 5.77717257, 5.71211551, 4.85979453,
       6.25953884, 6.21629892, 4.91644913, 6.09993016, 5.26597582,
       4.91548381, 5.44531985, 6.30098745, 6.24589044, 5.32076035,
       5.72560472, 6.88052902, 5.79466404, 5.64811037, 5.45784129,
       6.29524374, 5.76295667, 6.16699707, 5.88631825, 5.54997119,
       6.53030091, 5.47647068, 6.31844243, 6.2249628 , 6.31957107,
       4.40389812, 5.69437387, 6.36064468, 5.37490684, 5.47744099,
       6.07185192, 5.07218037, 5.97868781, 5.95516086, 5.17086439,
       5.77356659, 5.86070463, 6.30980141, 5.73348685, 6.23656054,
       6.12961807, 5.72560472, 6.18385363, 5.57963622, 5.92167513,
       6.85073597, 5.17262337, 5.7368759 , 4.49669742, 5.52190026,
       6.5587138 , 5.89928799, 5.98302526, 5.57692236, 5.84008145,
       6.0430071 , 5.16834769, 5.0528124 , 5.87223608, 5.4055833 ,
       6.35899673, 5.91123269, 5.57929123, 6.23322536, 6.42986

In [202]:
y_test

array([6., 7., 6., 6., 8., 5., 7., 6., 5., 5., 7., 6., 6., 6., 5., 4., 5.,
       5., 4., 6., 6., 7., 5., 6., 6., 6., 6., 6., 5., 6., 7., 6., 6., 7.,
       6., 5., 6., 7., 5., 6., 6., 4., 7., 3., 5., 5., 6., 6., 6., 6., 6.,
       6., 7., 6., 6., 7., 6., 5., 3., 5., 6., 6., 7., 5., 5., 6., 5., 6.,
       6., 5., 6., 6., 5., 6., 6., 5., 6., 6., 6., 6., 5., 4., 7., 5., 5.,
       7., 5., 6., 5., 7., 8., 6., 5., 5., 5., 6., 6., 5., 7., 5., 5., 6.,
       5., 4., 4., 6., 7., 7., 5., 5., 5., 5., 5., 6., 5., 8., 5., 7., 6.,
       6., 6., 5., 5., 6., 6., 6., 6., 7., 6., 5., 5., 6., 5., 6., 7., 8.,
       5., 6., 6., 5., 7., 6., 4., 5., 6., 5., 6., 6., 8., 6., 6., 6., 5.,
       4., 6., 6., 5., 7., 6., 6., 5., 7., 6., 7., 4., 5., 6., 6., 9., 5.,
       5., 5., 5., 7., 7., 6., 6., 6., 5., 6., 6., 6., 8., 5., 6., 6., 7.,
       7., 6., 6., 5., 7., 6., 7., 6., 7., 6., 5., 7., 5., 6., 5., 6., 5.,
       7., 6., 6., 7., 5., 5., 4., 6., 4., 6., 3., 6., 5., 7., 7., 5., 6.,
       6., 5., 6., 6., 5.